# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127UJdP017uBPtGU-ZhJuHxWSJYugZ3uV
"""

resposta = input("Deseja continuar no sistema? (Sim/Não): ")

if resposta.lower() == "sim":
    print("Continuando...")
else:
    print("Encerrando...")

uf = input("Digite a sigla do seu estado (ex: sp, rj): ")

uf_padronizada = uf.upper()

print(f"Estado cadastrado: {uf_padronizada}")

CUPOM_VALIDO = "DESCONTO10"
cupom_usuario = input("Digite o seu cupom promocional: ")

if cupom_usuario.upper() == CUPOM_VALIDO:
    print("Cupom aplicado com sucesso!")
else:
    print("Cupom inválido.")

nome = input("Digite o seu primeiro nome: ")

nome_limpo = nome.strip()

print(f"Nome limpo: {nome_limpo}")
print(f"Quantidade de caracteres: {len(nome_limpo)}")

email = input("Digite o seu e-mail: ")

if email.strip() == "":
    print("Erro: O campo e-mail não pode ficar em branco!")
else:
    print("E-mail cadastrado!")

USUARIO_CORRETO = "aluno@escola.com"

login = input("Digite seu login: ")

login_tratado = login.strip().lower()

if login_tratado == USUARIO_CORRETO:
    print("Login realizado com sucesso! Bem-vindo.")
else:
    print("Falha no login: Usuário incorreto.")